/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120224-g060fc4e3a5-20250709"
#endif /* AVUTIL_FFVERSION_H */
